UPDATE abyss_rank SET gp = gp-294 WHERE rank=18;
UPDATE abyss_rank SET gp = gp-254 WHERE rank=17;
UPDATE abyss_rank SET gp = gp-244 WHERE rank=16;
UPDATE abyss_rank SET gp = gp-237 WHERE rank=15;
UPDATE abyss_rank SET gp = gp-213 WHERE rank=14;
UPDATE abyss_rank SET gp = gp-98 WHERE rank=13;
UPDATE abyss_rank SET gp = gp-55 WHERE rank=12;
UPDATE abyss_rank SET gp = gp-27 WHERE rank=11;
UPDATE abyss_rank SET gp = gp-14 WHERE rank=10;